// const lecture = [
// {subjectCategory:"基礎科目",compulsory:true,name:"工学基礎実験",credits:1,Grade:",1年前期",priority:null},
// {subjectCategory:"基礎科目",compulsory:true,name:"微分積分I",credits:2,grade:"1年前期",priority:null},
// {subjectCategory:"基礎科目",compulsory:true,name:"線形代数I",credits:2,grade:"1年前期",priority:null},
// {subjectCategory:"基礎科目",compulsory:true,name:"力学",credits:2,grade:"1年前期",priority:null},
// {subjectCategory:"基礎科目",compulsory:false,name:"地学",credits:2,grade:"1年前期",priority:null},
// {subjectCategory:"基礎科目",compulsory:true,name:"微分積分Ⅱ",credits:2,grade:"1年後期",priority:null},
// {subjectCategory:"基礎科目",compulsory:true,name:"線形代数Ⅱ",credits:2,grade:"1年後期",priority:null},
// {subjectCategory:"基礎科目",compulsory:true,name:"確率統計",credits:2,grade:"1年後期",priority:null},
// {subjectCategory:"基礎科目",compulsory:true,name:"電磁気学基礎",credits:2,grade:"1年後期",priority:null},
// {subjectCategory:"基礎科目",compulsory:true,name:"情報処理入門",credits:2,grade:"1年後期",priority:null},
// {subjectCategory:"基礎科目",compulsory:true,name:"プログラミング基礎",credits:2,grade:"1年後期",priority:null},
// {subjectCategory:"基礎科目",compulsory:true,name:"技術表現法",credits:2,grade:"2年前期",priority:null},
// {subjectCategory:"基礎科目",compulsory:true,name:"微分方程式",credits:2,grade:"2年前期",priority:null},
// {subjectCategory:"基礎科目",compulsory:false,name:"振動波動",credits:2,grade:"2年前期",priority:null},
// {subjectCategory:"基礎科目",compulsory:false,name:"化学基礎",credits:2,grade:"2年前期",priority:null},
// {subjectCategory:"基礎科目",compulsory:false,name:"生物学基礎",credits:2,grade:"2年後期",priority:null},
// {subjectCategory:"基礎科目",compulsory:true,name:"電気電子・情報英語Ⅰ",credits:2,grade:"3年前期",priority:null},
// {subjectCategory:"基礎科目",compulsory:true,name:"電気電子・情報英語Ⅱ",credits:2,grade:"3年後期",priority:null},
// {subjectCategory:"基礎科目",compulsory:false,name:"現代物理学概論",credits:2,grade:"4年前期",priority:null},
// {subjectCategory:"基礎科目",compulsory:false,name:"技術経営概論",credits:2,grade:"4年前期",priority:null},
// {subjectCategory:"基礎科目",compulsory:false,name:"海外インターンシップ",credits:2,grade:"全期間",priority:null},
// {subjectCategory:"学科共通科目",compulsory:false,name:"物理数学基礎",credits:2,grade:"1年前期",priority:"応用物理"},
// {subjectCategory:"学科共通科目",compulsory:false,name:"情報数学",credits:2,grade:"1年後期",priority:"情報"},
// {subjectCategory:"学科共通科目",compulsory:false,name:"応用数学I",credits:2,grade:"2年前期",priority:null},
// {subjectCategory:"学科共通科目",compulsory:false,name:"量子力学概論",credits:2,grade:"2年前期",priority:"応用物理"},
// {subjectCategory:"学科共通科目",compulsory:false,name:"電気回路学基礎",credits:2,grade:"2年前期",priority:null},
// {subjectCategory:"学科共通科目",compulsory:false,name:"プログラミング応用",credits:2,grade:"2年前期",priority:null},
// {subjectCategory:"学科共通科目",compulsory:false,name:"微分方程式応用",credits:2,grade:"2年後期",priority:"応用物理"},
// {subjectCategory:"学科共通科目",compulsory:false,name:"統計力学概論",credits:2,grade:"2年後期",priority:"応用物理"},
// {subjectCategory:"学科共通科目",compulsory:false,name:"電子回路学基礎",credits:2,grade:"2年後期",priority:null},
// {subjectCategory:"学科共通科目",compulsory:false,name:"情報理論",credits:2,grade:"2年後期",priority:null},
// {subjectCategory:"学科共通科目",compulsory:false,name:"制御工学基礎",credits:2,grade:"2年後期",priority:null},
// {subjectCategory:"学科共通科目",compulsory:false,name:"数値解析",credits:2,grade:"3年前期",priority:null},
// {subjectCategory:"学科共通科目",compulsory:false,name:"信号処理",credits:2,grade:"3年前期",priority:null},
// {subjectCategory:"学科共通科目",compulsory:false,name:"光学",credits:2,grade:"3年前期",priority:"電気電子"},
// {subjectCategory:"学科共通科目",compulsory:false,name:"通信工学",credits:2,grade:"3年後期",priority:null},
// {subjectCategory:"学科共通科目",compulsory:false,name:"計算機支援設計製図",credits:2,grade:"3年後期",priority:"電気電子"},
// {subjectCategory:"学科共通科目",compulsory:true,name:"卒業研究",credits:8,grade:"4年",priority:null},
// {subjectCategory:"コース科目",compulsory:true,name:"情報工学実験I",credits:2,grade:"2年前期",priority:null},
// {subjectCategory:"コース科目",compulsory:false,name:"確率統計応用",credits:2,grade:"2年前期",priority:null},
// {subjectCategory:"コース科目",compulsory:false,name:"アルゴリズム論",credits:2,grade:"2年前期",priority:null},
// {subjectCategory:"コース科目",compulsory:false,name:"コンピュータアーキテクチャー",credits:2,grade:"2年前期",priority:null},
// {subjectCategory:"コース科目",compulsory:true,name:"プログラミング実践I",credits:2,grade:"2年後期",priority:null},
// {subjectCategory:"コース科目",compulsory:true,name:"情報工学実験Ⅱ",credits:2,grade:"2年後期",priority:null},
// {subjectCategory:"コース科目",compulsory:false,name:"多変量解析",credits:2,grade:"2年後期",priority:null},
// {subjectCategory:"コース科目",compulsory:false,name:"オペレーティングシステム",credits:2,grade:"2年後期",priority:null},
// {subjectCategory:"コース科目",compulsory:false,name:"論理回路",credits:2,grade:"2年後期",priority:null},
// {subjectCategory:"コース科目",compulsory:true,name:"プログラミング実践Ⅱ",credits:2,grade:"3年前期",priority:null},
// {subjectCategory:"コース科目",compulsory:false,name:"オートマン理論",credits:2,grade:"3年前期",priority:null},
// {subjectCategory:"コース科目",compulsory:false,name:"コンピュータネットワーク",credits:2,grade:"3年前期",priority:null},
// {subjectCategory:"コース科目",compulsory:false,name:"符号理論",credits:2,grade:"3年前期",priority:null},
// {subjectCategory:"コース科目",compulsory:false,name:"画像処理",credits:2,grade:"3年前期",priority:null},
// {subjectCategory:"コース科目",compulsory:false,name:"パターン認識",credits:2,grade:"3年前期",priority:null},
// {subjectCategory:"コース科目",compulsory:false,name:"暗号と情報セキュリティ",credits:2,grade:"3年前期",priority:null},
// {subjectCategory:"コース科目",compulsory:true,name:"情報工学セミナー",credits:2,grade:"3年後期",priority:null},
// {subjectCategory:"コース科目",compulsory:true,name:"情報工学実験Ⅲ",credits:2,grade:"3年後期",priority:null},
// {subjectCategory:"コース科目",compulsory:false,name:"ヒューマンインターフェイス",credits:2,grade:"3年後期",priority:null},
// {subjectCategory:"コース科目",compulsory:false,name:"人工知能",credits:2,grade:"3年後期",priority:null},
// {subjectCategory:"コース科目",compulsory:false,name:"機械学習",credits:2,grade:"3年後期",priority:null},
// {subjectCategory:"コース科目",compulsory:false,name:"データベース論",credits:2,grade:"3年後期",priority:null}
// ];

const app = new Vue({
	el: '#app',
	data: {
		main: [
			{take:true,id:1,subjectCategory:"基礎科目",compulsory:true,name:"工学基礎実験",credits:1,grade:"1年前期",priority:null},
            {take:true,id:2,subjectCategory:"基礎科目",compulsory:true,name:"微分積分I",credits:2,grade:"1年前期",priority:null},
            {take:true,id:3,subjectCategory:"基礎科目",compulsory:true,name:"線形代数I",credits:2,grade:"1年前期",priority:null},
            {take:true,id:4,subjectCategory:"基礎科目",compulsory:true,name:"力学",credits:2,grade:"1年前期",priority:null},
            {take:false,id:5,subjectCategory:"基礎科目",compulsory:false,name:"地学",credits:2,grade:"1年前期",priority:null},
            {take:true,id:6,subjectCategory:"基礎科目",compulsory:true,name:"微分積分Ⅱ",credits:2,grade:"1年後期",priority:null},
            {take:true,id:7,subjectCategory:"基礎科目",compulsory:true,name:"線形代数Ⅱ",credits:2,grade:"1年後期",priority:null},
            {take:true,id:8,subjectCategory:"基礎科目",compulsory:true,name:"確率統計",credits:2,grade:"1年後期",priority:null},
            {take:true,id:9,subjectCategory:"基礎科目",compulsory:true,name:"電磁気学基礎",credits:2,grade:"1年後期",priority:null},
            {take:true,id:10,subjectCategory:"基礎科目",compulsory:true,name:"情報処理入門",credits:2,grade:"1年後期",priority:null},
            {take:true,id:11,subjectCategory:"基礎科目",compulsory:true,name:"プログラミング基礎",credits:2,grade:"1年後期",priority:null},
            {take:true,id:12,subjectCategory:"基礎科目",compulsory:true,name:"技術表現法",credits:2,grade:"2年前期",priority:null},
            {take:true,id:13,subjectCategory:"基礎科目",compulsory:true,name:"微分方程式",credits:2,grade:"2年前期",priority:null},
            {take:false,id:14,subjectCategory:"基礎科目",compulsory:false,name:"振動波動",credits:2,grade:"2年前期",priority:null},
            {take:false,id:15,subjectCategory:"基礎科目",compulsory:false,name:"化学基礎",credits:2,grade:"2年前期",priority:null},
            {take:false,id:16,subjectCategory:"基礎科目",compulsory:false,name:"生物学基礎",credits:2,grade:"2年後期",priority:null},
            {take:true,id:17,subjectCategory:"基礎科目",compulsory:true,name:"電気電子・情報英語Ⅰ",credits:2,grade:"3年前期",priority:null},
            {take:true,id:18,subjectCategory:"基礎科目",compulsory:true,name:"電気電子・情報英語Ⅱ",credits:2,grade:"3年後期",priority:null},
            {take:false,id:19,subjectCategory:"基礎科目",compulsory:false,name:"現代物理学概論",credits:2,grade:"4年前期",priority:null},
            {take:false,id:20,subjectCategory:"基礎科目",compulsory:false,name:"技術経営概論",credits:2,grade:"4年前期",priority:null},
            {take:false,id:21,subjectCategory:"基礎科目",compulsory:false,name:"海外インターンシップ",credits:2,grade:"全期間",priority:null},
            {take:false,id:22,subjectCategory:"学科共通科目",compulsory:false,name:"物理数学基礎",credits:2,grade:"1年前期",priority:"応用物理"},
            {take:false,id:23,subjectCategory:"学科共通科目",compulsory:false,name:"情報数学",credits:2,grade:"1年後期",priority:"情報"},
            {take:false,id:24,subjectCategory:"学科共通科目",compulsory:false,name:"応用数学I",credits:2,grade:"2年前期",priority:null},
            {take:false,id:25,subjectCategory:"学科共通科目",compulsory:false,name:"量子力学概論",credits:2,grade:"2年前期",priority:"応用物理"},
            {take:false,id:26,subjectCategory:"学科共通科目",compulsory:false,name:"電気回路学基礎",credits:2,grade:"2年前期",priority:null},
            {take:false,id:27,subjectCategory:"学科共通科目",compulsory:false,name:"プログラミング応用",credits:2,grade:"2年前期",priority:null},
            {take:false,id:28,subjectCategory:"学科共通科目",compulsory:false,name:"微分方程式応用",credits:2,grade:"2年後期",priority:"応用物理"},
            {take:false,id:29,subjectCategory:"学科共通科目",compulsory:false,name:"統計力学概論",credits:2,grade:"2年後期",priority:"応用物理"},
            {take:false,id:30,subjectCategory:"学科共通科目",compulsory:false,name:"電子回路学基礎",credits:2,grade:"2年後期",priority:null},
            {take:false,id:31,subjectCategory:"学科共通科目",compulsory:false,name:"情報理論",credits:2,grade:"2年後期",priority:null},
            {take:false,id:32,subjectCategory:"学科共通科目",compulsory:false,name:"制御工学基礎",credits:2,grade:"2年後期",priority:null},
            {take:false,id:33,subjectCategory:"学科共通科目",compulsory:false,name:"数値解析",credits:2,grade:"3年前期",priority:null},
            {take:false,id:34,subjectCategory:"学科共通科目",compulsory:false,name:"信号処理",credits:2,grade:"3年前期",priority:null},
            {take:false,id:35,subjectCategory:"学科共通科目",compulsory:false,name:"光学",credits:2,grade:"3年前期",priority:"電気電子"},
            {take:false,id:36,subjectCategory:"学科共通科目",compulsory:false,name:"通信工学",credits:2,grade:"3年後期",priority:null},
            {take:false,id:37,subjectCategory:"学科共通科目",compulsory:false,name:"計算機支援設計製図",credits:2,grade:"3年後期",priority:"電気電子"},
            {take:true,id:38,subjectCategory:"学科共通科目",compulsory:true,name:"卒業研究",credits:8,grade:"4年",priority:null},
            {take:true,id:39,subjectCategory:"コース科目",compulsory:true,name:"情報工学実験I",credits:2,grade:"2年前期",priority:null},
            {take:false,id:40,subjectCategory:"コース科目",compulsory:false,name:"確率統計応用",credits:2,grade:"2年前期",priority:null},
            {take:false,id:41,subjectCategory:"コース科目",compulsory:false,name:"アルゴリズム論",credits:2,grade:"2年前期",priority:null},
            {take:false,id:42,subjectCategory:"コース科目",compulsory:false,name:"コンピュータアーキテクチャー",credits:2,grade:"2年前期",priority:null},
            {take:true,id:43,subjectCategory:"コース科目",compulsory:true,name:"プログラミング実践I",credits:2,grade:"2年後期",priority:null},
            {take:true,id:44,subjectCategory:"コース科目",compulsory:true,name:"情報工学実験Ⅱ",credits:2,grade:"2年後期",priority:null},
            {take:false,id:45,subjectCategory:"コース科目",compulsory:false,name:"多変量解析",credits:2,grade:"2年後期",priority:null},
            {take:false,id:46,subjectCategory:"コース科目",compulsory:false,name:"オペレーティングシステム",credits:2,grade:"2年後期",priority:null},
            {take:false,id:47,subjectCategory:"コース科目",compulsory:false,name:"論理回路",credits:2,grade:"2年後期",priority:null},
            {take:true,id:48,subjectCategory:"コース科目",compulsory:true,name:"プログラミング実践Ⅱ",credits:2,grade:"3年前期",priority:null},
            {take:false,id:49,subjectCategory:"コース科目",compulsory:false,name:"オートマン理論",credits:2,grade:"3年前期",priority:null},
            {take:false,id:50,subjectCategory:"コース科目",compulsory:false,name:"コンピュータネットワーク",credits:2,grade:"3年前期",priority:null},
            {take:false,id:51,subjectCategory:"コース科目",compulsory:false,name:"符号理論",credits:2,grade:"3年前期",priority:null},
            {take:false,id:52,subjectCategory:"コース科目",compulsory:false,name:"画像処理",credits:2,grade:"3年前期",priority:null},
            {take:false,id:53,subjectCategory:"コース科目",compulsory:false,name:"パターン認識",credits:2,grade:"3年前期",priority:null},
            {take:false,id:54,subjectCategory:"コース科目",compulsory:false,name:"暗号と情報セキュリティ",credits:2,grade:"3年前期",priority:null},
            {take:true,id:55,subjectCategory:"コース科目",compulsory:true,name:"情報工学セミナー",credits:2,grade:"3年後期",priority:null},
            {take:true,id:56,subjectCategory:"コース科目",compulsory:true,name:"情報工学実験Ⅲ",credits:2,grade:"3年後期",priority:null},
            {take:false,id:57,subjectCategory:"コース科目",compulsory:false,name:"ヒューマンインターフェイス",credits:2,grade:"3年後期",priority:null},
            {take:false,id:58,subjectCategory:"コース科目",compulsory:false,name:"人工知能",credits:2,grade:"3年後期",priority:null},
            {take:false,id:59,subjectCategory:"コース科目",compulsory:false,name:"機械学習",credits:2,grade:"3年後期",priority:null},
            {take:false,id:60,subjectCategory:"コース科目",compulsory:false,name:"データベース論",credits:2,grade:"3年後期",priority:null},
        ],
        other:{
            jinbun:0,
            syakai:0,
            shizen:0,
            hukugou:0,
            sports:0,
            kanagata:0,
            koukuu:0,
            tagakka:0,
            tadaigaku:0
        },
        requirements:[
            {name:"初年次セミナー",get:2,border:2,summable:2,result:"NG",left:2,message:""},
            {name:"人文科学",get:0,border:6,summable:24,result:"NG",left:6,message:""},
            {name:"社会科学",get:0,border:6,summable:24,result:"NG",left:6,message:""},
            {name:"自然科学",get:0,border:4,summable:24,result:"NG",left:4,message:""},
            {name:"複合領域",get:0,border:2,summable:24,result:"NG",left:2,message:""},
            {name:"スポーツ・健康科学",get:0,border:2,summable:24,result:"NG",left:2,message:""},
            {name:"外国語(英語＋2外0)",get:6,border:6,summable:6,result:"NG",left:6,message:""},
            {name:"工学概論",get:4,border:4,summable:4,result:"NG",left:4,message:""},
            {name:"技術と技術者の倫理",get:2,border:2,summable:2,result:"NG",left:2,message:""},
            {name:"★教養科目の合計",get:14,border:34,summable:38,result:"NG",left:34,message:""},
            {name:"基礎科目",get:0,border:29,summable:0,result:"NG",left:29,message:""},
            {name:"学科共通科目",get:0,border:28,summable:0,result:"NG",left:28,message:""},
            {name:"コース科目",get:0,border:36,summable:0,result:"NG",left:36,message:""},
            {name:"金型創生技術科目",get:0,border:0,summable:8,result:"NG",left:0,message:""},
            {name:"航空宇宙生産技術科目",get:0,border:0,summable:15,result:"NG",left:0,message:""},
            {name:"他学科開講科目",get:0,border:0,summable:10,result:"NG",left:0,message:""},
            {name:"他大学での履修科目",get:0,border:0,summable:10,result:"NG",left:0,message:""},
            {name:"総単位数",get:14,border:132,summable:0,result:"NG",left:132,message:""},

        ]
    },
    computed: {
        sum(){
            const data = this.main;
            const result = data.filter(lecture => lecture.take===true);
            let sum = 0;
            for(let i in result){
                sum += result[i].credits;
            } 
            return sum;
        }
    }
})